### ISSUE TITLE
chroniclemap hangs on table creation

### ISSUE THREAD

**Issue by subes** [invesdwin/invesdwin-context-persistence#25]
```
"37-1:ChartView_CPULIMIT" #304 prio=5 os_prio=0 cpu=2281154.20ms elapsed=73098.51s tid=0x00007f15bc003800 nid=0x3cbea9 runnable  [0x00007f14dec37000]
   java.lang.Thread.State: RUNNABLE
        at net.openhft.chronicle.hash.impl.util.jna.PosixMsync.msync(Native Method)
        at net.openhft.chronicle.hash.impl.util.jna.PosixMsync.msync(PosixMsync.java:36)
        at net.openhft.chronicle.hash.impl.VanillaChronicleHash.msync(VanillaChronicleHash.java:971)
        at net.openhft.chronicle.hash.impl.VanillaChronicleHash.msync(VanillaChronicleHash.java:954)
        at net.openhft.chronicle.map.ChronicleMapBuilder.commitChronicleMapReady(ChronicleMapBuilder.java:415)
        at net.openhft.chronicle.map.ChronicleMapBuilder.createWithNewFile(ChronicleMapBuilder.java:1846)
        at net.openhft.chronicle.map.ChronicleMapBuilder.createWithFile(ChronicleMapBuilder.java:1741)
        at net.openhft.chronicle.map.ChronicleMapBuilder.createPersistedTo(ChronicleMapBuilder.java:1586)
        at net.openhft.chronicle.map.ChronicleMapBuilder.createOrRecoverPersistedTo(ChronicleMapBuilder.java:1607)
        at net.openhft.chronicle.map.ChronicleMapBuilder.createOrRecoverPersistedTo(ChronicleMapBuilder.java:1597)
        at de.invesdwin.context.persistence.chronicle.PersistentChronicleMapFactory.createChronicleMap(PersistentChronicleMapFactory.java:55)
        at de.invesdwin.context.persistence.chronicle.PersistentChronicleMapFactory.newPersistentMap(PersistentChronicleMapFactory.java:34)
        at de.invesdwin.context.integration.persistentmap.APersistentMap.initializeTableLocked(APersistentMap.java:247)
        at de.invesdwin.context.integration.persistentmap.APersistentMap.initializeTable(APersistentMap.java:226)
        at de.invesdwin.context.integration.persistentmap.APersistentMap.initializeTableInitLocked(APersistentMap.java:208)
        at de.invesdwin.context.integration.persistentmap.APersistentMap.access$1(APersistentMap.java:206)
        at de.invesdwin.context.integration.persistentmap.APersistentMap$4.callRetry(APersistentMap.java:197)
        at de.invesdwin.context.integration.persistentmap.APersistentMap$4.callRetry(APersistentMap.java:1)
        at de.invesdwin.context.integration.retry.task.ARetryCallable$1.call(ARetryCallable.java:27)
        at de.invesdwin.context.integration.retry.internal.ExceptionCauseRetryCallback.doWithRetry(ExceptionCauseRetryCallback.java:47)
        at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:329)
        at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:209)
        at de.invesdwin.context.integration.retry.task.ARetryCallable.call(ARetryCallable.java:35)
        at de.invesdwin.context.integration.persistentmap.APersistentMap.getPreLockedDelegate(APersistentMap.java:199)
        at de.invesdwin.context.integration.persistentmap.APersistentMap.get(APersistentMap.java:456)
        at de.invesdwin.context.integration.persistentmap.APersistentMap.getOrLoad(APersistentMap.java:113)
        at de.invesdwin.context.persistence.timeseriesdb.storage.TimeSeriesStorage.getOrLoad_latestValueLookupTable(TimeSeriesStorage.java:250)
        at de.invesdwin.context.persistence.timeseriesdb.TimeSeriesStorageCache.getLatestValue(TimeSeriesStorageCache.java:582)
        at de.invesdwin.context.persistence.timeseriesdb.ATimeSeriesDB.getLatestValue(ATimeSeriesDB.java:183)
        at de.invesdwin.context.persistence.timeseriesdb.segmented.live.internal.PersistentLiveSegment.getLatestValue(PersistentLiveSegment.java:115)
        at de.invesdwin.context.persistence.timeseriesdb.segmented.live.internal.SwitchingLiveSegment.getLatestValue(SwitchingLiveSegment.java:242)
        at de.invesdwin.context.persistence.timeseriesdb.segmented.live.LiveSegmentedTimeSeriesStorageCache$1.apply(LiveSegmentedTimeSeriesStorageCache.java:36)
        at de.invesdwin.context.persistence.timeseriesdb.segmented.live.LiveSegmentedTimeSeriesStorageCache$1.apply(LiveSegmentedTimeSeriesStorageCache.java:1)
        at de.invesdwin.context.persistence.timeseriesdb.segmented.live.LiveSegmentedTimeSeriesStorageCache.getLatestValue(LiveSegmentedTimeSeriesStorageCache.java:175)
        at de.invesdwin.context.persistence.timeseriesdb.segmented.live.ALiveSegmentedTimeSeriesDB.getLatestValue(ALiveSegmentedTimeSeriesDB.java:333)
        at de.invesdwin.trading.broker.depot.compress.IsolatedEquityStorage$IsolatedEquityStorageFinalizer$1.readLatestValueFor(IsolatedEquityStorage.java:493)
        at de.invesdwin.trading.broker.depot.compress.IsolatedEquityStorage$IsolatedEquityStorageFinalizer$1.readLatestValueFor(IsolatedEquityStorage.java:1)
        at de.invesdwin.util.collections.loadingcache.historical.AGapHistoricalCache.readNewestValueFromDB(AGapHistoricalCache.java:530)
        at de.invesdwin.util.collections.loadingcache.historical.AGapHistoricalCache.loadValue(AGapHistoricalCache.java:159)
        - locked <0x00000000e0b6cf58> (a de.invesdwin.trading.broker.depot.compress.IsolatedEquityStorage$IsolatedEquityStorageFinalizer$1)
        at de.invesdwin.util.collections.loadingcache.historical.AGapHistoricalCache$$Lambda$1206/0x0000000841473c40.evaluateGeneric(Unknown Source)
        at de.invesdwin.util.collections.loadingcache.historical.AHistoricalCache$ValuesMap.lambda$0(AHistoricalCache.java:558)
        at de.invesdwin.util.collections.loadingcache.historical.AHistoricalCache$ValuesMap$$Lambda$1179/0x00000008413d2440.apply(Unknown Source)
        at de.invesdwin.util.collections.loadingcache.historical.AHistoricalCache$2.loadValue(AHistoricalCache.java:307)
        at de.invesdwin.util.collections.loadingcache.historical.AHistoricalCache$2.loadValue(AHistoricalCache.java:1)
        at de.invesdwin.util.collections.loadingcache.ALoadingCache$1.apply(ALoadingCache.java:54)
        at de.invesdwin.util.collections.loadingcache.map.ASynchronizedMapLoadingCache.get(ASynchronizedMapLoadingCache.java:38)
        at de.invesdwin.util.collections.loadingcache.ADelegateLoadingCache.get(ADelegateLoadingCache.java:33)
        at de.invesdwin.util.collections.loadingcache.ADelegateLoadingCache.get(ADelegateLoadingCache.java:33)
        at de.invesdwin.util.collections.loadingcache.historical.AHistoricalCache$ValuesMap.get(AHistoricalCache.java:548)
        at de.invesdwin.util.collections.loadingcache.historical.AHistoricalCache$ValuesMap.get(AHistoricalCache.java:1)
        at de.invesdwin.util.collections.loadingcache.historical.query.internal.core.DefaultHistoricalCacheQueryCore.getEntry(DefaultHistoricalCacheQueryCore.java:38)
        at de.invesdwin.util.collections.loadingcache.historical.query.internal.core.DefaultHistoricalCacheQueryCore.getValue(DefaultHistoricalCacheQueryCore.java:68)
        at de.invesdwin.util.collections.loadingcache.historical.query.internal.core.ACachedEntriesHistoricalCacheQueryCore.getValue(ACachedEntriesHistoricalCacheQueryCore.java:108)
        at de.invesdwin.util.collections.loadingcache.historical.query.internal.core.AFilteringDelegateHistoricalCacheQueryCore.getValue(AFilteringDelegateHistoricalCacheQueryCore.java:78)
        at de.invesdwin.util.collections.loadingcache.historical.query.internal.HistoricalCacheQuery.getValue(HistoricalCacheQuery.java:108)
        at de.invesdwin.util.collections.loadingcache.historical.query.internal.HistoricalCacheQueryWithFuture.getValue(HistoricalCacheQueryWithFuture.java:36)
        at de.invesdwin.util.collections.loadingcache.historical.query.internal.adjust.AdjustingHistoricalCacheQuery.getValue(AdjustingHistoricalCacheQuery.java:168)
        at de.invesdwin.util.collections.loadingcache.historical.query.internal.filter.FilteringHistoricalCacheQuery.getValue(FilteringHistoricalCacheQuery.java:77)
        at de.invesdwin.trading.broker.depot.compress.IsolatedEquityStorage.getLatestValue(IsolatedEquityStorage.java:126)
        at de.invesdwin.trading.charts.richclient.service.strategy.chart.data.EquityChangeIndicator.convert(EquityChangeIndicator.java:112)
        at de.invesdwin.trading.charts.richclient.service.strategy.chart.data.EquityChangeIndicator.access$0(EquityChangeIndicator.java:106)
        at de.invesdwin.trading.charts.richclient.service.strategy.chart.data.EquityChangeIndicator$2.getValue(EquityChangeIndicator.java:173)
        at de.invesdwin.trading.charts.richclient.swing.chart.panel.series.SeriesDatasetProvider.getValue(SeriesDatasetProvider.java:44)
        at de.invesdwin.context.client.swing.jfreechart.plot.dataset.list.item.SlaveXYDataItemOHLC.innerLoadValue(SlaveXYDataItemOHLC.java:68)
        at de.invesdwin.context.client.swing.jfreechart.plot.dataset.list.item.SlaveXYDataItemOHLC.loadValue(SlaveXYDataItemOHLC.java:64)
        at de.invesdwin.context.client.swing.jfreechart.plot.dataset.list.item.MasterOHLCDataItem.loadSlaveItems(MasterOHLCDataItem.java:90)
        at de.invesdwin.context.client.swing.jfreechart.plot.dataset.list.MasterLazyDatasetList.updateTrailingItems(MasterLazyDatasetList.java:737)
        at de.invesdwin.context.client.swing.jfreechart.plot.dataset.list.MasterLazyDatasetList.update(MasterLazyDatasetList.java:680)
        - locked <0x00000000ba543720> (a de.invesdwin.trading.charts.richclient.swing.chart.panel.ChartView$4)
        at de.invesdwin.trading.charts.richclient.swing.chart.panel.ChartView.updateData(ChartView.java:473)
        at de.invesdwin.trading.charts.richclient.swing.chart.panel.ChartView.access$10(ChartView.java:452)
        at de.invesdwin.trading.charts.richclient.swing.chart.panel.ChartView$8$1.run(ChartView.java:336)
        at de.invesdwin.util.concurrent.internal.WrappedRunnable.run(WrappedRunnable.java:47)
        at java.util.concurrent.Executors$RunnableAdapter.call(java.base@11.0.15/Executors.java:515)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.15/ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.15/ThreadPoolExecutor.java:628)
        at de.invesdwin.util.concurrent.internal.WrappedThreadFactory.lambda$0(WrappedThreadFactory.java:48)
        at de.invesdwin.util.concurrent.internal.WrappedThreadFactory$$Lambda$466/0x00000008402f8440.run(Unknown Source)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(java.base@11.0.15/Thread.java:829)

   Locked ownable synchronizers:
        - <0x00000000b86a5b78> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        - <0x00000000e11c4488> (a java.util.concurrent.ThreadPoolExecutor$Worker)

```

**Comment by subes** [comment]
switching back to DISK_SAFE (leveldb) as the default
